### ISSUE TITLE
Font is too high for tabs

### ISSUE THREAD

**Issue by Shogu** [moktavizen/material-darker-jdownloader#1]
Hello and many thanks for your theme, i crawled all ovber the web to get one and yours is  the prettier, and so far better than all  embbed dark themes.

I use it on Fedora with a Flatpak version of Jdownloader.

Everything works so fine but there is a minor issue with the font size into the tabs : let see this screenshot 
![Capture d’écran du 2024-05-27 19-49-37](https://github.com/moktavizen/material-darker-jdownloader/assets/696880/034185c8-e172-43b5-97b7-001c7e72573f)

> 

Anay way to fix this?  Using font scaling in the setting spanel, for example?

I am also searching for a way to replace the defaut tray icon , wich looks ugly on Gnome.

Thanks a lot : )

Greetings from France!

**Comment by moktavizen** [comment]
Hello

Thank you for your kind words, and greeting from Indonesia!
also sorry for the late response, I've been focusing on my final project for Uni for these past few months.

Unfortunately I can't reproduce your issue, it looks fine on me.

![image](https://github.com/moktavizen/material-darker-jdownloader/assets/89829361/0513acd9-c9f4-4cb0-b7f5-600da7a26ab0)

Maybe you can try tweaking the font setting in JDownloader or in GNOME itself

![image](https://github.com/moktavizen/material-darker-jdownloader/assets/89829361/2786359d-ffb8-4feb-a212-c5479972e9b9)

**Comment by moktavizen** [comment]
can you try installing the theme again? i change the base theme and from my own test, the bar is rendered correctly

**Comment by Shogu** [comment]
Hi!

Thanks a lot for your work!

I tried the new theme, but it still fails. Probably because, as you wrote on your github mainpage, i am using the Flatpak version of Jdownloader.

**Comment by moktavizen** [comment]
Thanks for your confirmation
