### ISSUE TITLE
Progress bar and rows too big

### ISSUE THREAD

**Issue by Kayn2106** [moktavizen/material-darker-jdownloader#10]
Hi, is this the default progress bar dimension ? From your screenshots they seemed smaller, I mean normal size...

Thanks for your time

![brave_screenshot (2)](https://github.com/user-attachments/assets/18e753d4-ea8c-47a3-bcc3-1554df5fe9e3)

**Comment by moktavizen** [comment]
Go to `Advanced Settings` and reset the value of `Custom Table Row Height`.
