### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by Drsexo** [moktavizen/material-darker-jdownloader#2]
The progress % gets covered by the white progress bar, any fix ?
![image](https://github.com/moktavizen/material-darker-jdownloader/assets/101467921/eff29a9d-22d3-4913-b43b-0471e480bd73)

**Comment by moktavizen** [comment]
What's your OS? can't reproduce your issue on my Linux system.

![image](https://github.com/moktavizen/material-darker-jdownloader/assets/89829361/8a361b3e-d096-4c1f-a327-687cfa901288)

**Comment by moktavizen** [comment]
can you try installing the theme again? i change the base theme and from my own test, the bar is rendered correctly
