### ISSUE TITLE
[Question] Comparison with other projects

### ISSUE THREAD

**Issue by GATOQSECOMIO** [moktavizen/material-darker-jdownloader#3]
What differences exist between this project compared to the ones I mention later? Any performance improvements?

[dracula/jdownloader2](https://github.com/dracula/jdownloader2/)
[Vinylwalk3r/JDownloader-2-Dark-Theme](https://github.com/Vinylwalk3r/JDownloader-2-Dark-Theme)

Congrats for the project, its really nice.
PD: Sorry for my bad english.

**Comment by moktavizen** [comment]
> What differences exist between this project compared to the ones I mention later?

- Different color palette, neutral dark
- Different icons, over 250 icons are changed to flat themed icons

> Any performance improvements?

No. This is only a theme, it will only change JDownloader cosmetics
