### ISSUE TITLE
Flat is not working

### ISSUE THREAD

**Issue by Alexo88** [moktavizen/material-darker-jdownloader#6]
i dont know why, and if is only me, but flat minimal theme is not working there are a full windows.

**Comment by moktavizen** [comment]
can you provide more context? a screenshot will be helpful too

**Comment by moktavizen** [comment]
Closed due to inactivity.

**Comment by Alexo88** [comment]
![image](https://github.com/user-attachments/assets/c5fef6bf-f359-476d-9601-9f499da62ff4)
look
