### ISSUE TITLE
Please add support for customizing font scale factor

### ISSUE THREAD

**Issue by n3thshan** [moktavizen/material-darker-jdownloader#8]
After scouring through the internet I found that JDownloader cannot change font size at runtime for LAF themes and that it requires separate config files. This [link ](https://www.formdev.com/flatlaf/how-to-customize) was provided but is too complicated for me and most likely many other average users. It would be great for you to include a description in the README.md to change font scale factor easily! TIA!

**Comment by moktavizen** [comment]
Try to change the scale for your whole system, by default JDownloader follow the system scaling.

**Comment by n3thshan** [comment]
> Try to change the scale for your whole system, by default JDownloader follow the system scaling.

oh thats a bummer. that is not possible because i like the default windows scaling. Its just that i want jdownloader to have a bit more larger font. No need for icons to scale

**Comment by moktavizen** [comment]
I found possible workarounds, but it needs more testing.

**Comment by moktavizen** [comment]
If you want to scale only your JDownloader, Create or
edit `JDownloader2.vmoptions` on your `<installation-directory>`, then add
`-Dsun.java2d.uiScale=200%` inside of it.

**Comment by n3thshan** [comment]
this works! the fonts look nice but wish the icons were scalable though cos they look stretched and pixelated.
