### ISSUE TITLE
Hoster icons in the linkgrabber tab are not visible

### ISSUE THREAD

**Issue by n3thshan** [moktavizen/material-darker-jdownloader#9]
![Screenshot (3)](https://github.com/user-attachments/assets/0d4ccf57-ceeb-431a-803f-86ffbb9ad4b3)

As you can see the theme does not render the hoster icons in hoster column. It does on the side panel but not for each individual file/part.

**Comment by n3thshan** [comment]
It does appear on the Downloads tab however

![Screenshot (4)](https://github.com/user-attachments/assets/02a951b1-035e-45e5-a4cb-1900db74cd20)

**Comment by n3thshan** [comment]
This [quote ](https://board.jdownloader.org/showpost.php?p=462063&postcount=7) from the JD2 forums may help you solve the issue.

**Comment by moktavizen** [comment]
did this also happens on any other sites?

**Comment by n3thshan** [comment]
> did this also happens on any other sites?

yes. even on youtube.

**Comment by moktavizen** [comment]
Strange, YouTube works on me. Try resetting the value of `Favicons Failed Hosts` and `Favicons Last Refresh` in Advanced Settings.

**Comment by n3thshan** [comment]
Nope it did not fix the issue. To clarify things, I am not talking about the hoster icons on the right side of the screen in Linkgrabber tab. I am referring to the ones in the Hoster column in the middle interface.

**Comment by n3thshan** [comment]
After testing again, it did work but then disappeared when I relaunched the app/expanded and retracted the folders. Also on that note, without any scaling, the hoster icons appear to be low res and pixelated too (the ones on the right side of the screen)

**Comment by n3thshan** [comment]
https://github.com/user-attachments/assets/75c48a49-ed4f-453c-876f-78e9d74b2176

Some files have it but as you can see in the video, they dissapear when i just hover above them

**Comment by moktavizen** [comment]
Reset `look and feel` to default in Advanced Settings, and see if the issue happens on default theme too. Don't worry you can go back to this theme without reinstalling it, just set `look and feel` too `FLATLAF_DARK` again.

**Comment by n3thshan** [comment]
resetting look and feel worked temporarily and then after I retracted the folder and expanded it again, icons went away

**Comment by moktavizen** [comment]
I don't think I can do much here. I make this theme without touching any Favicon/Hoster icons and the logic behind retrieving it. Try to report this issue in [JDownloader Forum](https://board.jdownloader.org/forumdisplay.php?f=12), since this issue also happens when using default theme.
